package: url_scheme
version: '1.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/schemes
pages:
    yrewrite/url_scheme:
        title: 'URL Scheme-AddOn'
        perm: admin
        icon: rex-icon fa-exchange


requires:
    packages:
        yrewrite: '>=1.0.0'
