package: yrewrite_scheme
version: '1.0.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/schemes
pages:
    yrewrite/yrewrite_scheme:
        title: 'YRewrite Scheme'
        perm: admin
        icon: rex-icon fa-exchange


requires:
    packages:
        yrewrite: '>=1.0.0'
