package: yrewrite_scheme
version: '2.0.0-beta1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/schemes
pages:
    yrewrite/yrewrite_scheme:
        title: 'YRewrite Scheme'
        perm: admin
        icon: rex-icon fa-exchange


requires:
    packages:
        yrewrite: '>=2.1.0'
